use_frameworks!

target 'OEMentions_Example' do
  pod 'OEMentions', :path => '../'

  target 'OEMentions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.3.1'
  end
end
